services:
  # Opensearch
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.16.0
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=BkK8[(SdJ*,#&G4g
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - internal
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.16.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - internal
  # Fluent bit
  fluent-bit:
    image: fluent/fluent-bit:3.1.6
    container_name: fluent-bit
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/envoy.conf:/fluent-bit/etc/envoy.conf
      - ./fluent-bit/containers.conf:/fluent-bit/etc/containers.conf
    depends_on:
      - opensearch
    networks:
      - internal
  # Envoy
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:contrib-v1.29.1
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/lua/ratelimit.lua:/etc/lua/ratelimit.lua
      - ./envoy/lua/lib:/var/lib/lua
      - /tmp/spire-agent/public:/tmp/spire-agent/public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: envoy
    ports:
      - "10000:10000"
      # - "10001:10001"
      - "10002:10002"
      - "8379:8379"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "debug"]
    depends_on:
      - fluent-bit
      - dummy-api
      - webdis
    networks:
      - internal
      - webdis
  # Dummy API
  dummy-api:
    container_name: dummy-api
    build: ./dummy-api
    environment:
      DB_PATH: /var/lib/api/items.db
    ports:
      - "8888:8888"
    volumes:
      - ./dummy-api/items.db:/var/lib/api/items.db
    networks:
      - internal
  # Alerting API
  alerting:
    container_name: alerting
    build: ./alerting
    ports:
      - "31415:31415"
    networks:
      - internal
  # cAdvisor
  #cadvisor:
  #  container_name: cadvisor
  #  image: gcr.io/cadvisor/cadvisor:v0.49.1
  #  volumes:
  #    - /:/rootfs:ro
  #    - /var/run:/var/run:ro
  #    - /sys:/sys:ro
  #    - /var/lib/docker/:/var/lib/docker:ro
  #    - /dev/disk/:/dev/disk:ro
  #  ports:
  #    - "8080:8080"
  #  restart: always
  #  networks:
  #    - internal
  webdis:
    container_name: webdis
    image: nicolas/webdis:0.1.22
    ports:
      - "7379:7379"
    networks:
      - webdis
networks:
  internal:
  webdis:
volumes:
  opensearch-data:
